'use client';
import {useState} from 'react';
import './DocumentViewer.css';
import './DocumentViewerDetails.css';
import GuideDetails from './GuideDetails';

type Job={file_name:string};
type Document={id:string;title:string;document_type:string;department?:string;question_original?:string;answer_original?:string;content_masked?:string;page_count?:number;chunk_count:number;metadata?:Record<string,unknown>;status:string;[key:string]:unknown};
type Complaint=Record<string,unknown>;
const labels=[['application_number','신청번호'],['receipt_number','접수번호'],['application_at','신청일시'],['received_at','접수일시'],['expected_completion_at','처리완료 예정일'],['summary','민원요지'],['handler_masked','담당자'],['department','처리부서'],['processor_masked','처리자'],['notification_at','처리결과 통보일'],['answer_confirmed_at','답변 확인일'],['application_channel','신청경로'],['complaint_kind','민원종류'],['processing_result','처리구분'],['public_status','공개여부'],['processing_period_days','처리기간(일)'],['notification_method','답변 통지방식']];
function complaintData(doc:Document){return((doc.metadata?.complaint||{})as Complaint);}
function field(doc:Document,key:string){const value=doc[key]??complaintData(doc)[key];if(Array.isArray(value))return value.join(', ');return value==null||value===''?'—':String(value).replace('T',' ').replace(/\+00:00$/,'');}
function list(doc:Document,key:string){const value=doc[key]??complaintData(doc)[key];return Array.isArray(value)?value.map(String):[];}

export default function DocumentViewer({job,documents,loading,close,removeDocument,removeUpload}:{job:Job,documents:Document[],loading:boolean,close:()=>void,removeDocument:(id:string)=>Promise<void>,removeUpload:()=>Promise<void>}){const[selected,setSelected]=useState('');const active=documents.find(doc=>doc.id===(selected||documents[0]?.id));return <div className="viewer-back"><section className="document-viewer"><header><div><span className="eyebrow">UPLOADED COMPLAINTS</span><h2>{job.file_name}</h2><p>저장된 민원 {documents.length}건의 질의·답변과 주요 정보를 확인합니다.</p></div><button className="viewer-close" aria-label="닫기" onClick={close}>×</button></header><div className="viewer-body"><aside className="document-list">{loading?<p className="empty-doc">불러오는 중…</p>:documents.length===0?<p className="empty-doc">저장된 민원이 없습니다.</p>:documents.map((doc,index)=><button className={active?.id===doc.id?'active':''} onClick={()=>setSelected(doc.id)} key={doc.id}><small>민원 {index+1} · 청크 {doc.chunk_count||0}개</small><strong>{doc.title}</strong><span>{doc.department||'부서 미지정'} · {doc.status==='ready'?'검색 가능':doc.status}</span></button>)}<button className="delete-upload" onClick={removeUpload}>업로드 자료 전체 삭제</button></aside><article className="document-detail">{active?(active.document_type==='guide'?<GuideDetails document={active} remove={removeDocument}/>:<><div className="detail-title"><div><span className="type-chip">민원</span><h3>{active.title}</h3></div><button className="delete-doc" onClick={()=>removeDocument(active.id)}>민원 삭제</button></div><div className="complaint-info">{labels.map(([key,label])=><div className={key==='summary'?'wide':''} key={key}><small>{label}</small><strong>{field(active,key)}</strong></div>)}</div>{list(active,'attachments').length>0&&<section><h4>첨부파일</h4><div className="attachment-list">{list(active,'attachments').map(name=><span key={name}>▧ {name}</span>)}</div></section>}<section><h4>민원내용</h4><p>{active.question_original||'분리된 민원내용이 없습니다.'}</p></section><section><h4>관련 법령</h4><div className="law-list">{list(active,'related_laws').length?list(active,'related_laws').map(law=><span key={law}>{law}</span>):<span>추출된 관련 법령이 없습니다.</span>}</div></section><section><h4>처리결과</h4><p>{active.answer_original||'분리된 처리결과가 없습니다.'}</p></section><details><summary>마스킹 본문·전체 메타데이터</summary><section><h4>마스킹 본문</h4><p>{active.content_masked||'본문이 없습니다.'}</p></section><pre>{JSON.stringify(active.metadata||{},null,2)}</pre></details></>):<div className="empty-detail">왼쪽 목록에서 민원을 선택해 주세요.</div>}</article></div></section></div>}
