import {cookies} from 'next/headers';

export type UserProfile={id:string;email:string;full_name:string;department:string;position:string;office_phone:string;role:'admin'|'user';approval_status:'pending'|'approved'|'rejected';created_at:string};
type AuthUser={id:string;email?:string};
type AuthSession={access_token:string;refresh_token:string;expires_in:number;user:AuthUser};

function config(){const url=(process.env.SUPABASE_URL||'').replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY||'';if(!url||!key)throw new Error('SUPABASE_NOT_CONFIGURED');return{url,key};}
async function request<T>(path:string,init:RequestInit={}){const{url,key}=config();const response=await fetch(`${url}${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(`AUTH_${response.status}: ${await response.text()}`);const text=await response.text();return(text?JSON.parse(text):null)as T;}
export async function signUp(input:{email:string;password:string;fullName:string;department:string;position:string;officePhone:string}){const user=await request<AuthUser>('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email:input.email,password:input.password,email_confirm:true})});try{await request('/rest/v1/user_profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:user.id,email:input.email.toLowerCase(),full_name:input.fullName,department:input.department,position:input.position,office_phone:input.officePhone,role:'user',approval_status:'pending'})});}catch(error){await request(`/auth/v1/admin/users/${user.id}`,{method:'DELETE'}).catch(()=>null);throw error;}return{status:'pending'};}
export async function signIn(email:string,password:string){const session=await request<AuthSession>('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});await setSessionCookies(session);return getProfile(session.user.id);}
export async function signOut(){const jar=await cookies();jar.delete('chutjul_access');jar.delete('chutjul_refresh');}
async function setSessionCookies(session:AuthSession){const jar=await cookies();const secure=process.env.NODE_ENV==='production';jar.set('chutjul_access',session.access_token,{httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:session.expires_in||3600});jar.set('chutjul_refresh',session.refresh_token,{httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:60*60*24*30});}
async function refreshSession(refreshToken:string){const session=await request<AuthSession>('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:refreshToken})});await setSessionCookies(session);return session.user;}
async function authUser(){const jar=await cookies();let token=jar.get('chutjul_access')?.value;if(token){try{const{url,key}=config();const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`},cache:'no-store'});if(response.ok)return await response.json()as AuthUser;}catch{}}const refresh=jar.get('chutjul_refresh')?.value;if(!refresh)return null;try{return await refreshSession(refresh)}catch{await signOut();return null;}}
export async function getProfile(id:string){const rows=await request<UserProfile[]>(`/rest/v1/user_profiles?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);return rows[0]||null;}
export async function currentProfile(){const user=await authUser();return user?getProfile(user.id):null;}
export async function requireProfile(options:{approved?:boolean;admin?:boolean}={}){const profile=await currentProfile();if(!profile)throw new Error('AUTH_REQUIRED');if(options.approved&&profile.approval_status!=='approved')throw new Error('ACCOUNT_NOT_APPROVED');if(options.admin&&profile.role!=='admin')throw new Error('ADMIN_REQUIRED');return profile;}
export async function serviceRequest<T>(path:string,init:RequestInit={}){return request<T>(path,init);}
